# Configuration file

####################
# block
####################

block {
    I:"Brew Kettle ID"=3940
    I:"Ferment Barrel ID"=3938
    I:"Fruit Press (Bottom Part) ID"=3946
    I:"Fruit Press (Top Part) ID"=3941
}


####################
# potions
####################

potions {
    I:"Potion Tipsy ID"=50
}


####################
# villager
####################

villager {
    I:"Brewer ID"=10
}


