# Configuration file

####################
# block
####################

block {
    I:"Grape (Block) ID"=3893
    I:"Grape Leaves ID"=3894
    I:"Grape Vine (Seedling) ID"=3896
    I:"Grape Vine (Trunk) ID"=3895
}


####################
# item
####################

item {
    I:"Grape Seeds ID"=5004
    I:"Grape Wine (Bottle) ID"=5005
    I:"Grape Wine (Bucket) ID"=5006
    I:"Grapes ID"=5003
}


