# Configuration file

####################
# block
####################

block {
    I:"Hop Vine ID"=3892
}


####################
# item
####################

item {
    I:"Ale (Bottle) ID"=5009
    I:"Ale (Bucket) ID"=5010
    I:"Hop Seeds ID"=5008
    I:"Hops ID"=5007
}


