# Configuration file

####################
# block
####################

block {
    I:"Rice (Block)"=3891
}


####################
# item
####################

item {
    I:Onigiri=5014
    I:"Rice ID"=5011
    I:"Sake (Bottle) ID"=5012
    I:"Sake (Bucket) ID"=5013
}


