name = "Tech It"
author = "Tomodachi94"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb67373dee4e7860ca260f7b73e0058eec9d09fd610ad5149e2c641160e83bf0"

[versions]
forge = "9.11.1.965"
minecraft = "1.6.4"

[options]
acceptable-game-versions = ["1.6.2", "CB 1.6.4-R2.0"]
