name = "Tech It"
author = "Tomodachi94"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a884beadf8144c66229aa3475aed86aa81aba380f68783315bb1894033c1250"

[versions]
forge = "9.11.1.1345"
minecraft = "1.6.4"

[options]
acceptable-game-versions = ["1.6.2"]
