name: New suggestion
description: Suggest new additions to the modpack!
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new addition!
        Please submit this form once per suggestion, unless they are closely related.
  - type: checkboxes
    id: is-available-for-this-minecraft
    attributes:
      label: Is this mod/addition available for Minecraft 1.6.4?
      options:
        - label: "Yes"
          required: true
  - type: textarea
    id: name
    attributes:
      label: What is the name of the thing you want added?
      placeholder: a project's name
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summarize what the thing is or does.
      placeholder: Adds new items, optimization mod, fixes a bug, ...
    validations:
      required: true
  - type: textarea
    id: url
    attributes:
      label: Where can the mod be found?
      placeholder: https://example.com, https://pastebin.com/..., https://github.com/...
    validations:
      required: true
